# Copyright (C) 2020 tt.bot dev team
# 
# This file is part of tt.bot's extension runner.
# 
# tt.bot's extension runner is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# tt.bot's extension runner is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with tt.bot's extension runner.  If not, see <http://www.gnu.org/licenses/>.

name: Release on GitHub packages

on:
  release:
    types: [released]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Node.js
        uses: actions/setup-node@v1
        with:
            node-version: ">=10.0.0"
      - name: npm install
        run: npm install
        env:
            CI: true
      - name: Set packag
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}